version: '3'
services:
  backend:
    build:
      context: ./food-commerce-back-end
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./food-commerce
    ports:
      - "8080:80 "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
